### PR TITLE
Add modified elasticsearch's docker-compose.yml project with custom d…

### PR DESCRIPTION
**Pull request by timothyjlaurent**
Add modified Elasticsearch's docker-compose.yml project with custom dockerfile containing installation of Learning to Rank plugin.

This should be compatible with Invitae's Rancher environment when we want to push it to Sandbox or production.

### CODE REVIEW

**Review by mattvitae — CHANGES_REQUESTED** [review]
Thank you @timothyjlaurent for the contribution!

I have pulled the issue branch, and it `docker-compose up` seems to start the containers fine on my laptop. However, i'm don't understand why there are two ES containers. Can you please add some information about the configuration either in the README file or in the docker-compose.yml?

Thank you!

**Comment by mattvitae** [comment]
@timothyjlaurent I would also like the ES container to be in a subfolder from the top-level, since we're going to keep all of the code in a single repo (unless we're not, in which case, we need some more specific repo names...)

**Comment by mattvitae** [comment]
I also think it's probably useful to have a test corpus (e.g. <100kb) of text that we can have as a test index.

**Comment by timothyjlaurent** [comment]
Ok, I moved the docker stuff into the `elasticsearch` directory and added some test data and a script to load it.

**Review by mattvitae — APPROVED** [review]
Thanks for these updates @timothyjlaurent !

**Pull request merged**
